openapi: 3.0.1
info:
  title: HL7® FHIR® InsurancePlan resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
  - url: https://gcp-hcls-test.apigee.net/v1/ghc/r4
tags:
  - name: InsurancePlan
paths:
  /InsurancePlan:
    get:
      tags:
        - InsurancePlan
      parameters:
        - name: address
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: address-city
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: address-country
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: address-postalcode
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: address-state
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: address-use
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: administered-by
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: endpoint
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: identifier
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: name
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: owned-by
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: status
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: type
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: _format
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          x-consoleDefault: application/json
      responses:
        "200":
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InsurancePlan'
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
    post:
      tags:
        - InsurancePlan
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      requestBody:
        content:
          'application/fhir+json;charset=utf-8':
            schema:
              $ref: '#/components/requestBodies/InsurancePlan'
        required: false
      responses:
        200:
          description: Success
          content: {}
      x-codegen-request-body-name: body
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
  /InsurancePlan/{id}:
    get:
      tags:
        - InsurancePlan
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      responses:
        200:
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                $ref: '#/components/schemas/InsurancePlan'
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
    put:
      tags:
        - InsurancePlan
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          'application/fhir+json;charset=utf-8':
            schema:
              $ref: '#/components/requestBodies/InsurancePlan'
        required: false
      responses:
        200:
          description: Success
          content: {}
      x-codegen-request-body-name: body
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
    delete:
      tags:
        - InsurancePlan
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
  /InsurancePlan/{id}/_history:
    get:
      tags:
        - InsurancePlan
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: _count
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: _since
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
  /InsurancePlan/{id}/_history/{vid}:
    get:
      tags:
        - InsurancePlan
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: vid
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                $ref: '#/components/schemas/InsurancePlan'
      security:
        - OAuthV2B2B:
            - system/InsurancePlan.read
            - system/InsurancePlan.write
components:
  schemas:
    Account_text:
      required:
        - div
        - status
      type: object
      properties:
        status:
          minLength: 1
          type: string
        div:
          minLength: 1
          type: string
    Account_meta:
      required:
        - tag
      type: object
      properties:
        tag:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_type_coding'
    InsurancePlan:
      required:
        - id
        - meta
        - name
        - resourceType
        - text
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        text:
          $ref: '#/components/schemas/Account_text'
        name:
          minLength: 1
          type: string
        meta:
          $ref: '#/components/schemas/Account_meta'
  requestBodies:
    InsurancePlan:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InsurancePlan'
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://gcp-hcls-test.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            system/InsurancePlan.read: Read permissions for InsurancePlan demographics.
            system/InsurancePlan.write: Write permissions for InsurancePlan demographics.
