openapi: 3.0.1
info:
  title: HL7® FHIR® MedicationKnowledge resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
  - url: https://gcp-hcls-test.apigee.net/v1/ghc/r4
tags:
  - name: MedicationKnowledge
paths:
  /MedicationKnowledge:
    get:
      tags:
        - MedicationKnowledge
      parameters:
        - name: classification
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: classification-type
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: code
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: doseform
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: ingredient
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: ingredient-code
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: manufacturer
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: monitoring-program-name
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: monitoring-program-type
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: monograph
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: monograph-type
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: source-cost
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: status
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: _format
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          x-consoleDefault: application/json
      responses:
        "200":
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicationKnowledge'
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
    post:
      tags:
        - MedicationKnowledge
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      requestBody:
        content:
          'application/fhir+json;charset=utf-8':
            schema:
              $ref: '#/components/requestBodies/MedicationKnowledge'
      responses:
        200:
          description: Success
          content: {}
      x-codegen-request-body-name: body
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
  /MedicationKnowledge/{id}:
    get:
      tags:
        - MedicationKnowledge
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      responses:
        200:
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                $ref: '#/components/schemas/MedicationKnowledge'
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
    put:
      tags:
        - MedicationKnowledge
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          'application/fhir+json;charset=utf-8':
            schema:
              $ref: '#/components/requestBodies/MedicationKnowledge'
      responses:
        200:
          description: Success
          content: {}
      x-codegen-request-body-name: body
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
    delete:
      tags:
        - MedicationKnowledge
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
  /MedicationKnowledge/{id}/_history:
    get:
      tags:
        - MedicationKnowledge
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: _count
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: _since
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
  /MedicationKnowledge/{id}/_history/{vid}:
    get:
      tags:
        - MedicationKnowledge
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: vid
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                $ref: '#/components/schemas/MedicationKnowledge'
      security:
        - OAuthV2B2B:
            - system/MedicationKnowledge.read
            - system/MedicationKnowledge.write
components:
  schemas:
    Account_text:
      required:
        - div
        - status
      type: object
      properties:
        status:
          minLength: 1
          type: string
        div:
          minLength: 1
          type: string
    Account_coverage:
      required:
        - reference
      type: object
      properties:
        reference:
          minLength: 1
          type: string
    Account_meta:
      required:
        - tag
      type: object
      properties:
        tag:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_type_coding'
    Account_type_coding:
      required:
        - code
        - display
        - system
      properties:
        system:
          minLength: 1
          type: string
        code:
          minLength: 1
          type: string
        display:
          minLength: 1
          type: string
    ActivityDefinition_valueCodeableConcept:
      required:
        - coding
      type: object
      properties:
        coding:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_type_coding'
    MedicationKnowledge_contained:
      required:
        - id
        - name
        - resourceType
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        name:
          minLength: 1
          type: string
    MedicationKnowledge_amount:
      required:
        - unit
        - value
      type: object
      properties:
        value:
          type: number
        unit:
          minLength: 1
          type: string
    MedicationKnowledge:
      required:
        - amount
        - code
        - contained
        - doseForm
        - id
        - manufacturer
        - meta
        - resourceType
        - status
        - synonym
        - text
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        text:
          $ref: '#/components/schemas/Account_text'
        contained:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/MedicationKnowledge_contained'
        code:
          $ref: '#/components/schemas/ActivityDefinition_valueCodeableConcept'
        status:
          minLength: 1
          type: string
        manufacturer:
          $ref: '#/components/schemas/Account_coverage'
        doseForm:
          $ref: '#/components/schemas/ActivityDefinition_valueCodeableConcept'
        amount:
          $ref: '#/components/schemas/MedicationKnowledge_amount'
        synonym:
          type: array
          items:
            properties: {}
        meta:
          $ref: '#/components/schemas/Account_meta'
  requestBodies:
    MedicationKnowledge:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MedicationKnowledge'
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://gcp-hcls-test.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            system/MedicationKnowledge.read: Read permissions for MedicationKnowledge demographics.
            system/MedicationKnowledge.write: Write permissions for MedicationKnowledge demographics.
