openapi: 3.0.1
info:
  title: HL7® FHIR® OrganizationAffiliation resource API documentation
  description: "Fast Healthcare Interoperability Resources (HL7® FHIR®, pronounced \"Fire\"\
  ) defines a set of \"Resources\" that represent granular clinical concepts. The resources\
  \ can be managed in isolation, or aggregated into complex documents. Technically, FHIR is\
  \ designed for the web; the resources are based on simple JSON structures, with an\
  \ http-based RESTful protocol where each resource has predictable URL. Where possible,\
  \ open internet standards are used for data representation. The FHIR® R4 API docs are part\
  \ of the FHIR® Specifications (v4.0.1: R4). The is the current published version. This\
  \ section contains API docs for the R4 resources required to meet the CMS and ONC\
  \ interoperability and data access requirements. API docs for other resources can be added\
  \ by API publishers on request. \n"
servers:
  - url: https://gcp-hcls-test.apigee.net/v1/ghc/r4
tags:
  - name: OrganizationAffiliation
paths:
  /OrganizationAffiliation:
    get:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: active
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: date
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
        - name: email
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: endpoint
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: identifier
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: location
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: network
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: participating-organization
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: phone
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: primary-organization
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: role
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: service
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: specialty
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: telecom
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: _format
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          x-consoleDefault: application/json
      responses:
        "200":
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationAffiliation'
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
    post:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      requestBody:
        content:
          'application/fhir+json;charset=utf-8':
            schema:
              $ref: '#/components/requestBodies/OrganizationAffiliation'
      responses:
        200:
          description: Success
          content: {}
      x-codegen-request-body-name: body
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
  /OrganizationAffiliation/{id}:
    get:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
      responses:
        200:
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrganizationAffiliation'
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
    put:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          'application/fhir+json;charset=utf-8':
            schema:
              $ref: '#/components/requestBodies/OrganizationAffiliation'
      responses:
        200:
          description: Success
          content: {}
      x-codegen-request-body-name: body
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
    delete:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
  /OrganizationAffiliation/{id}/_history:
    get:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: _count
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: _since
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
  /OrganizationAffiliation/{id}/_history/{vid}:
    get:
      tags:
        - OrganizationAffiliation
      parameters:
        - name: Accept
          in: header
          description: The Accept request-header field can be used to specify certain media types which are acceptable for the response.
          schema:
            type: string
            default: application/fhir+json;charset=utf-8
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: vid
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            'application/fhir+json;charset=utf-8':
              schema:
                $ref: '#/components/schemas/OrganizationAffiliation'
      security:
        - OAuthV2B2B:
            - system/OrganizationAffiliation.read
            - system/OrganizationAffiliation.write
components:
  schemas:
    Account_text:
      required:
        - div
        - status
      type: object
      properties:
        status:
          minLength: 1
          type: string
        div:
          minLength: 1
          type: string
    Account_identifier:
      required:
        - system
        - value
      properties:
        system:
          minLength: 1
          type: string
        value:
          minLength: 1
          type: string
    Account_servicePeriod:
      required:
        - end
        - start
      type: object
      properties:
        start:
          minLength: 1
          type: string
        end:
          minLength: 1
          type: string
    Account_coverage:
      required:
        - reference
      type: object
      properties:
        reference:
          minLength: 1
          type: string
    Account_subject:
      required:
        - display
        - reference
      properties:
        reference:
          minLength: 1
          type: string
        display:
          minLength: 1
          type: string
    Account_meta:
      required:
        - tag
      type: object
      properties:
        tag:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_type_coding'
    Account_type_coding:
      required:
        - code
        - display
        - system
      properties:
        system:
          minLength: 1
          type: string
        code:
          minLength: 1
          type: string
        display:
          minLength: 1
          type: string
    ActivityDefinition_telecom:
      required:
        - system
        - use
        - value
      properties:
        system:
          minLength: 1
          type: string
        value:
          minLength: 1
          type: string
        use:
          minLength: 1
          type: string
    ActivityDefinition_coding:
      required:
        - code
        - system
      properties:
        system:
          minLength: 1
          type: string
        code:
          minLength: 1
          type: string
    ActivityDefinition_jurisdiction:
      properties:
        coding:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ActivityDefinition_coding'
    AdverseEvent_category:
      properties:
        coding:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_type_coding'
    Appointment_basedOn:
      required:
        - reference
      properties:
        reference:
          minLength: 1
          type: string
    OrganizationAffiliation:
      required:
        - active
        - code
        - endpoint
        - healthcareService
        - id
        - identifier
        - location
        - meta
        - network
        - organization
        - participatingOrganization
        - period
        - resourceType
        - specialty
        - telecom
        - text
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        text:
          $ref: '#/components/schemas/Account_text'
        identifier:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_identifier'
        active:
          type: boolean
        period:
          $ref: '#/components/schemas/Account_servicePeriod'
        organization:
          $ref: '#/components/schemas/Account_coverage'
        participatingOrganization:
          $ref: '#/components/schemas/Account_coverage'
        network:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_subject'
        code:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ActivityDefinition_jurisdiction'
        specialty:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/AdverseEvent_category'
        location:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Account_subject'
        healthcareService:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Appointment_basedOn'
        telecom:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ActivityDefinition_telecom'
        endpoint:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Appointment_basedOn'
        meta:
          $ref: '#/components/schemas/Account_meta'
  requestBodies:
    OrganizationAffiliation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrganizationAffiliation'
  securitySchemes:
    OAuthV2B2B:
      type: oauth2
      description: Security scheme for B2B flow using authorization code flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://gcp-hcls-test.apigee.net/oauth/v2/accesstoken?grant_type=client_credentials'
          scopes:
            system/OrganizationAffiliation.read: Read permissions for OrganizationAffiliation demographics.
            system/OrganizationAffiliation.write: Write permissions for OrganizationAffiliation demographics.
